### ISSUE TITLE
font size in replay

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/dataportal#121]
When we updated the software on srx (5id) the font size in replay was something along the lines of 5 point or so.  Absurdly small.  @gjwillms was able to fix this by changing the default font options with qtconfig.  He suggested that gnome and kde have baseline settings for qt apps and xfce does not.

This would be a valuable thing to add to the docs

**Comment by tacaswell** [comment]
email from Garth:

> For your information, I fixed this on xf05id1-ws4 by changing the default font options with qtconfig.  Could be that gnome and kde have baseline settings for qt apps and xfce does not.

**Comment by gjwillms** [comment]
For completeness, my procedure sets the system-wide default qt application font to "Sans Serif,18,-1,5,50,0,0,0,0,0," which beamline scientists are likely to be able to read.  This applies to all text within the widgets, but does not affect the font used for the title of each individual widget in the pane--including the titles of tabs.  I've been unable to discover from whence, in the display manager's config, this font specification is derived by, I assume, enaml/qt.  Perhaps setting the widget's minimum font size to 12 or 14pts would resolve the issue (Xfce seems to default to a 9-pt sans serif font that, as @ericdill notes, is absurd.)?

**Comment by danielballan** [comment]
It looks easy to control fonts using [enaml stylesheets](http://nucleic.github.io/enaml/docs/dev_guides/stylesheets.html#font-size) but I can't see how to implement a _minimum_ font size that still respects a (larger) qt default.
