### ISSUE TITLE
There should be a way to fetch events as a generator

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/dataportal#127]
This came up as Pavol tried to fetch events from a Header with ~400 2048x2048 images on this MacBook. Until every beamline offers a way for users to work remotely on machines with copious RAM, we can't aggressively load everything all the time.

Options:
- `DataBroker.fetch_events` simply returns a generator. Upside: simple, downside: `len(events)` doesn't work.
- Add `DataBroker.fetch_events_as_generator` or something like that.
- `DataBroker.fetch_events` returns something that _has_ a generator.

Workaround I sent to Pavol for now:

```
from dataportal.broker.simple_broker import fill_event
from metadatastore.api import find_events


def events_generator(header):
    "Return a generator of Events. Large (nonscalar) data is lazy-loaded."
    descriptors = header.event_descriptors
    if len(descriptors) > 1:
        raise NotImplmementedError
    descriptor, = descriptors
    raw_events = find_events(descriptor=descriptor)
    for e in raw_events[::-1]:  # in chronological order
        fill_event(e)
        yield e
```

**Comment by danielballan** [comment]
In an in-person conversation, @tacaswell and @arkilic are +1 on this.

**Comment by ghost** [comment]
:+1: my exchange account stopped working so I wasn't getting any notifications. Full blessing
