### ISSUE TITLE
Proposed change to *broker* (not MDS) Event Document layout

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/dataportal#129]
This proposes a change affecting the presentation of the data, not the on-disk representation.

Watching the broker API in use today, @dchabot and I think databroker's Event Documents should be changed from a dictionary of tuples to pair of dictionaries with identical keys.

Proposed API:

```
    event.data['pe1_image_lightfield']  # the image array
    event.timestamps['pe1_image_lightfield']  # the associated timestamps
```

This does _not_ require a change of the underlying MDS Document.

For the majority of use cases, we care about measured values much more than timestamps. Slicing into the `(value, timestamp)` tuple, as in

```
    images = [event.data['pe1_image_lightfield'][0] for event in events]
```

adds another mental step to the long unpacking.

**Comment by tacaswell** [comment]
Provisional :+1: to this.  There is no reason we can't have both `data_stream` and `timestamp_stream` vs `data`?

**Comment by danielballan** [comment]
And an in-person :+1: from @arkilic.

**Comment by ericdill** [comment]
:+1: in principle.  It would be nice to shorten the word `timestamps` though, especially since tab-complete isn't necessarily a thing that people are familiar with.  Any major issues with something like `ts`?

**Comment by danielballan** [comment]
I slightly prefer `timestamps` but I am OK with `ts`.
