### ISSUE TITLE
Teach DataBroker[key] about uids 

### ISSUE THREAD

**Issue by pavoljuhas** [NSLS-II/dataportal#130]
The `DataBroker[key]` syntax supports only slices or `scan_id` integers which may not be unique.  Please, let it also digest the `run_start_uid`, `run_stop_uid` values of the document object, and ideally their partials strings.

``` python
from dataportal.broker import DataBroker as db
header = db[-1]
assert header == db[header.run_start_uid]
assert header == db[header.run_start_uid[:7]]
```

**Comment by danielballan** [comment]
OK, that makes sense. Will do.
