### ISSUE TITLE
Plot on multiple y axes

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/dataportal#148]
There should be an option to display multiple scalars on multiple y axis of a scan in the same plot. This setting should be maintained, when a new scan is selected.

requested by @skalbfleisch

**Comment by tacaswell** [comment]
http://matplotlib.org/1.4.3/mpl_toolkits/axes_grid/users/overview.html#axisartist-with-parasiteaxes or just http://matplotlib.org/examples/api/two_scales.html

**Comment by ericdill** [comment]
Moved to NSLS-II/replay#21
