### ISSUE TITLE
Update simple_broker

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/dataportal#16]
`search` should be called `get_events` and it should take `headers` _or_ `start_time`, `end_time` as arguments.

A new function `search_runs` should pass through to MDS `find_header`.

**Comment by ericdill** [comment]
Perhaps call the function `search_runs` to simply `explore`

**Comment by danielballan** [comment]
`get_events(*args)` accepts one or more headers

**Comment by danielballan** [comment]
`explore` and/or `search_runs` returns a list of pairs:

```
>>> explore(user=...)
[(begin, end), (begin, end)]
```

**Comment by danielballan** [comment]
One more function:

```
find_event_stream(...)
```

which returns a generator.

**Comment by danielballan** [comment]
Superceded by #57
