### ISSUE TITLE
Slow DataBroker performance at HXN

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/dataportal#169]
cc @danielballan @tacaswell @klauer 

Here is output from profiling the fetching of events from scan 512 at HXN.

These results are generated with the `yappi` Python profiling package along with [the script](https://gist.github.com/anonymous/6e7f8a00f3366a22fc3b#file-profile_scan_512-py) used to generate the results.

All function calls sorted (roughly) by call stack: https://gist.github.com/anonymous/6e7f8a00f3366a22fc3b#file-hxn-scan-512-yappi-txt-L8

All function calls sorted by total time spent in that function: https://gist.github.com/anonymous/6e7f8a00f3366a22fc3b#file-hxn-scan-512-yappi-txt-L313

Function calls sorted by total time in that function with running cumulative time: https://gist.github.com/anonymous/6e7f8a00f3366a22fc3b#file-hxn-scan-512-yappi-txt-L620

Note:
The cumulative time is not perfect, as it shows a total of ~70 seconds while the total running time is ~106 seconds, but it is accurate enough to first order

For scan 512, we appear to be calling `__setattr__` on mongoengine.base.document.Document a whopping 1.3 million times!
## Results with yappi
1. using DataBroker API: 106 seconds [results](https://gist.github.com/anonymous/6e7f8a00f3366a22fc3b)
2. using metadatastore API: 86 seconds [results](https://gist.github.com/745cf17a4208cafa7f71)
3. using metadatastore without converting mongoengine stuff to `metadatastore.Document` 16.6 seconds [results](https://gist.github.com/anonymous/773d89e7bb10ffee37aa#file-scan-512-no-_as_document-yappi-txt-L266) 
   1. Note: [see changes to _as_document](https://gist.github.com/anonymous/773d89e7bb10ffee37aa#file-commands-py-L361) only for benchmarking purposes

**Comment by danielballan** [comment]
Take a look at the IPython line profiler extension.

**Comment by ericdill** [comment]
[edit] updated original post

**Comment by tacaswell** [comment]
I suspect the problem is that as we are building the event documents it is de-referencing (the full depth) of the event descriptor and run start documents.  There is a way to get tell pymongo to not do thins (basically `QuerySet.no_dereference`, but we will have to patch up the the event documents to re-add that stuff).  

I'll have this sorted out by the end of the day.

**Comment by cowanml** [comment]
Can also limit the depth of dereferencing with  select_related(max_depth=N)...

**Comment by tacaswell** [comment]
Have this down to ~3-4s

**Comment by ericdill** [comment]
Closed by NSLS-II/metadatastore#134
