### ISSUE TITLE
Correct syntax documentation in ophyd for scan with multiple motors

### ISSUE THREAD

**Issue by cmazzoli** [NSLS-II/dataportal#170]
Hi guys,
this evening we saw a problem while trying to perform a linear scan involving two motors..
This syntax
scan([m1, m2], [-10, -5], [10, 5], 20)
as suggested in
http://tacaswell.github.io/docs/ophyd/scan_api.html
doesn't seem to work. Please refer to:
https://controlsweb01.nsls2.bnl.gov/xf23id1-log/index.html#4358_3
for a screenshot.
It is quite urgent... the experiment ends on sunday 04/26 at 16:00!!

**Comment by tacaswell** [comment]
Does

``` python
scan([m1, m2], [[-10, -5], [10, 5]], [20, 20])
```

Work?

**Comment by tacaswell** [comment]
See http://nsls-ii.github.io/ophyd/scan_api.html#ophyd.userapi.scan_api.AScan which is the current 'canonical' docs.

Should be

``` python
scan([[m1, m2]], [[-10, -5]], [[10, 5]], 20)
```

**Comment by cmazzoli** [comment]
I thing that I tried without success (because I got the syntax wrong the
first time) but I am not sure..sorry I am bit tired..
Thanks.
Cla

**Comment by tacaswell** [comment]
A bit more poking at the code I think the following will work:

``` python
ascan([[m1, m2]], [[start1, start2]], [[stop1, stop2]], [[npts]])
```

Note all of the `[]`, none of them are optional.

**Comment by cmazzoli** [comment]
It works, thank you!
Cla

**Comment by tacaswell** [comment]
This api is deprecated.
