### ISSUE TITLE
Mechanism to load part of the dataset

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/dataportal#185]
This comes from HXN.  Given a flyscan dataset (e.g., scan 1395), loading it through dataportal takes ~140 seconds.  Much of this time is spent in h5py loading stuff from disk.  While the beamline scientists are doing scans, they are primarily concerned about the three ROI entries in the hdf5 file, not the entire data set.  It seems important to either make the data loading more efficient or provide a mechanism to load only part of the dataset.  A syntax that I proposed and they (HXN) liked was lazy loading of the data by datakey.  Something like: 

``` python
ss1395 = StepScan[1395]
# lazy load roi1
ch1 = ss1395['Ch1 [9300:9600']
# lazy load roi2
ch2 = ss1395['Ch2 [9300:9600']
#...etc
```

I have no idea how feasible this is, and I suspect it is strongly dependent on how their data is stored on disk?

**Comment by ghost** [comment]
This is a good idea. Actually, this is how I accomplished slicing on web services with mongo backends before(as long as not multi-threaded application since cursor is not really thread safe).We can add the indexing and slicing feature on the mongo cursor.

```
class Indexable(object):
    def __init__(self,it):
        self.it = iter(it)
        self.already_computed=[]
    def __iter__(self):
        for elt in self.it:
            self.already_computed.append(elt)
            yield elt
    def __getitem__(self,index):
        try:
            max_idx=index.stop
        except AttributeError:
            max_idx=index
        n=max_idx-len(self.already_computed)+1
        if n>0
            self.already_computed.extend(itertools.islice(self.it,n))
        return self.already_computed[index]   
```

```
it=Indexable(mongo_crsr)
```

So we can do things like:

```
print(it[2:12:2])
```

**Comment by tacaswell** [comment]
We can also push on filestore a bit and have it return proxy objects instead of filled out numpy arrays.

**Comment by ericdill** [comment]
This should be folded in to the API redo #195
