### ISSUE TITLE
Proposal: make run starts "taggable"

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/dataportal#194]
The `db[]` interface borrows some ideas from git. For example, you can use partial uids. What if we pushed this analogy further, introducing the analog of "git tag" but for scan IDs. We could namespace them a little ('csx.my-tag') to contain the clutter.

@tacaswell is going to _hate_ this.... :imp:

**Comment by tacaswell** [comment]
Why am I going to hate this?  It does not make as much sense as git tagging as there is no natural 'parent' or 'child' runs.  We had always talked about keeping another collection of scanid <-> text mappings.

**Comment by danielballan** [comment]
I was half-kidding. I'm glad you don't hate it. I had forgotten any earlier conversation about this. Would you be +1 on a PR implementing this in the near future? Would be nice for demos:

`db['xpcs-example-data']`

**Comment by tacaswell** [comment]
I would expect `db['some-tag-name']` to return many headers.

**Comment by ghost** [comment]
Why don't you add the tags to run_start docs then? I think the first iteration of mds had tags but I was advised to get rid off them :hand:

**Comment by tacaswell** [comment]
@arkilic Because we want to keep the core collections an write-once, tags need to be more dynamic.

**Comment by ghost** [comment]
I know they are write-once, I fought besides you for them to stay that way. You can have a tags collection with docs that hold uid to headers. Make this collection update-able which gives you the dynamic nature. For this kind of stuff, updates work well in mongo

**Comment by danielballan** [comment]
I think that's what Tom proposed. Same page?

**Comment by ghost** [comment]
Yup, I just saw his comment, have not seen that one. My only concern is this is another query that is added to the header retrieval so I am not sure if this will cause performance issues for many headers. Having mentioned my concern, I say it is up to you since performance requirement is driven by the analysis side.

**Comment by tacaswell** [comment]
The performance bottle necks we have seen are all from hitting the db once-per-event, hitting a few times per run start is noise :wink: .

If we are really getting bit by that we can always do a de-normalized cache layer.

**Comment by ghost** [comment]
I'm worried about the kind of beam line that will have as many headers as hxn events. Yup, but I sure hopen adding more indexing doesn't hurt the header write speed too much :)

**Comment by tacaswell** [comment]
moved to https://github.com/NSLS-II/metadatastore/issues/234
