### ISSUE TITLE
argh, timezones!

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/dataportal#210]
In #209, @danielballan fixed the large problem of times going in to pandas unlocalized.  However, a problem remains because a user could be doing data analysis in a different timezone from where the data was collected.  That timezone can be found in `metadatastore.conf.connection_config['timezone']`.  That is probably what we should localize on, but let's think about it.

**Comment by tacaswell** [comment]
Now tracked in https://github.com/NSLS-II/databroker/issues/59
