### ISSUE TITLE
Write broker-style API to archiver that returns documents

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/dataportal#211]
We recently thought of this as another light-weight package, but I think it could probably live happily in dataportal.

Suggested API:

```
dataportal.archiver.get_period(start_time, end_time, pvs)
dataportal.archiver.get_events(header, pvs)
dataportal.archiver.get_table(header, pvs)
```

where `pvs` is a list of strings. We could add `get_table`, too, but I think we can wait. We may not need it or want users to use it because I suspect that in almost every case their next step will be to _align_ that data. So the workflow will probably be:

```
dm = DataMuxer.from_events(broker.get_events(header))
dm.append_events(archiver.get_events(header, pvs))
dm.bin_on('whatever')
```

Here is a snippet of code I wrote while helping users at CSX. It might be a useful starting point.

```
import uuid
from metadatastore.doc import Document

def new_uid():
    return str(uuid.uuid4())

dummy_desc = Document('descriptor', uid='dummy', data_keys={'ring_current': {'source': 'dummy'}})
ring_data_as_events = [Document('event', time=t, timestamps={'ring_current': t}, data={'ring_current': d},
                                uid=new_uid(), descriptor=dummy_desc)
                       for d, t in zip(ring_data['ring_current'], unix_times)]
```

**Comment by tacaswell** [comment]
Done in https://github.com/NSLS-II/databroker/pull/51
