### ISSUE TITLE
replay refactor

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/dataportal#27]
Instead of having the `DataMuggler` emit a signal which is connected up to the `models` (as currently implemented), have a (set?) of timers on replay which trigger polling of MDS/databroker.  If there is new data, grab it,  add it to the  muggler and then re-generate the plots.

This has the benefits of simplifying the logic of replay  and means we do not need a Qt aware version of `DataMuggler`.

The cost is that we abandon the idea of having flexible signal/slot based pipelines and make all of the data updating/plotting synchronous.

**Comment by danielballan** [comment]
Can we close this? @ericdill @tacaswell 

Instead of Qt signaling, we will have queues, and the rest of this seems to be built into the new replay.

**Comment by ericdill** [comment]
yes this is done
