### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/dataportal#3]
@ericdill @tacaswell The examples don't seem to work on the current code. For sphinx, they have to either be working or be removed. Can you take a look?

**Comment by danielballan** [comment]
I fixed one Exception myself, but this one seems like a job for whoever wrote the example:

```
Exception occurred:
  File "/Users/danielallan/Documents/Repos/databroker/examples/find_multiple_scans.py", line 66, in <module>
    plt.scatter(data_obj.energy, data_obj.sclr_ch5)
AttributeError: 'Event' object has no attribute 'energy'
```

**Comment by ericdill** [comment]
1. Which mongo db are you connected to?
2. If it is not the one at csx, how did you get data into it?

**Comment by ericdill** [comment]
After actually looking at the example, this one will only work if you're connected to the metadatastore on csx as it is trying to load actual experimental data.  Get rid of the example for now and I'll work on one that uses synthetic data

**Comment by danielballan** [comment]
Great. Thanks.
