### ISSUE TITLE
Support slicing by scan_id

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/dataportal#86]
Does it make any sense to also support slicing by scan_id?  e.g. `db[6210:6220]`

**Comment by ericdill** [comment]
@tacaswell replied:
I think that will turn into a can of worms as the scan_id is not guaranteed to be unique or continuous

**Comment by ericdill** [comment]
@arkilic replied:
I think @ericdill  is right. Any scientist we have ever spoken, including @stuwilkins,  suggested we provide them with this feature.We might not ensure a uniqueness on scan_id but scan_id has to be unique_with some other feature e.g. owner

**Comment by ericdill** [comment]
I replied:
@tacaswell : @danielballan and I discussed a nice way to provide uniqueness for the DataBroker slicing syntax.  One way to do this is to have some sort of state management in the DataBroker so that you can do stuff like:

``` python
from dataportal.broker import DataBroker as db

db.user = 'edill'
db.beamline = 'csx'
db.start_time = '2015-01-01'
db.end_time = '2015-02-01'
db.sample = 'CBr4'

# Now that the databroker object has some notion of cutting down the results, you can use
# slicing syntax which will give you the results that you actually care about.

tons_o_runs = db[15:30]
```

**Comment by ericdill** [comment]
Then replied again:
What I forgot to say, but you can probably intuit, is that the slicing syntax then respects whatever state is set by the user. 

The actual syntax probably needs to be something else like `db.search_terms['user'] = 'edill'` or whatever, but we can argue about the syntax later

**Comment by ericdill** [comment]
@arkilic replied:
This is exactly what I had in mind when I wrote unique_with :+1:

**Comment by ericdill** [comment]
@danielballan  replied:
My take: slicing by scan ID, like label-based slicing in pandas, is problematic but very useful. I think it should be added, but not until we add functionality for setting "defaults" like

```
DataBroker.owner = 'dallan'
```

and so on that will make scan ID slicing meaningful.

I don't see that happening in time for next week's deployments, and I don't want to rush it. Let's merge these "safe" features and approach the trickier features with more care and many tests.

**Comment by stuwilkins** [comment]
+1 to that. This type is definitely needed, but we have to focus on Deployment at the moment.

S
On Feb 27, 2015, at 11:23 AM, Eric Dill <notifications@github.com<mailto:notifications@github.com>> wrote:

@danielballanhttps://github.com/danielballan replied:
My take: slicing by scan ID, like label-based slicing in pandas, is problematic but very useful. I think it should be added, but not until we add functionality for setting "defaults" like

DataBroker.owner = 'dallan'

and so on that will make scan ID slicing meaningful.

I don't see that happening in time for next week's deployments, and I don't want to rush it. Let's merge these "safe" features and approach the trickier features with more care and many tests.

**Comment by tacaswell** [comment]
closing as will not implement
