### ISSUE TITLE
Support searching headers by data key (that is, PV ID or PV alias)

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/dataportal#88]
This is the mongo query we need to build in DataBroker to make this possible:

```
db.event_descriptor.find({'data_keys.point_det':{$exists: true}}).
```

**Comment by danielballan** [comment]
Addressed in part by #107, but it is still not possible to search by PV string -- only by alias. @arkilic can you whip up the query we need for this?

**Comment by ghost** [comment]
Got it! What would the search argument be? pvs=['motor1.rbv', 'motor2.rbv']?

**Comment by danielballan** [comment]
It would be the actual PV string, stored in the source key of data_keys.
Like "PV:blahblahblah". #details

One PV at a time, for now, because if there are multiple we need to think
about "and" and "or."

**Comment by danielballan** [comment]
Per conversation with @arkilic and I think @tacaswell, we are punting on searching PV string until someone needs it. It is tricky and it will definitely be slow. That is, you can `find_headers(data_key='motor1'`) but you cannot `find_headers(pv='PV:{blah}...)`.

**Comment by ghost** [comment]
Writing a small extension that keeps track of timestamp, alias, PV is quite straight forward to implement [if someone needs it!!!]
