### ISSUE TITLE
Handling Errorbars in Replay the correct way

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/dataportal#97]
Right now every line on the plot gets its own `ScalarModel` which holds a reference to a `LineArtist`.  This is not going to work when we need to show error bars on the data because the axes.errorbar function returns a tuple of three (See end of issue). It is unclear how to update the data in an errorbar plot without resorting to an entirely new call to axes.errorbar.  

Note that this is not a high priority.

```
Say the function call is this ::

   ret = ax.errorbar(x, y, yerr=1, xerr=1)

- ret[0] will be a matplotlib.lines.Line2D object which reresents the "data"
  portion of the plot, e.g. ``<matplotlib.lines.Line2D at 0x7f64e2a223d0>``
- ret[1] will be a list of matplotlib.lines.Line2D objects which represents
  the "caps" to the error bars in order (left_x, right_x, bottom_y, top_y), e.g. ::

    (<matplotlib.lines.Line2D at 0x7f64e2be0150>,
     <matplotlib.lines.Line2D at 0x7f64e2be0410>,
     <matplotlib.lines.Line2D at 0x7f64e2bfcad0>,
     <matplotlib.lines.Line2D at 0x7f64e2bf2a10>)

- ret[2] will be a list of matplotlib.collections.LineCollection objects which
  represents the error bar lines in order (x, y), e.g. ::

    (<matplotlib.collections.LineCollection at 0x7f64e2a6d390>,
     <matplotlib.collections.LineCollection at 0x7f64e2c81a90>)

```

**Comment by tacaswell** [comment]
I have a PR in mpl to make this behave better (https://github.com/matplotlib/matplotlib/pull/3944)

**Comment by tacaswell** [comment]
and you just need to update all the pieces.

**Comment by ericdill** [comment]
Yeah it's the 'update all the pieces' that seems like it is challenging to do correctly

**Comment by ericdill** [comment]
Moved to NSLS-II/replay#11
