### ISSUE TITLE
Current master does not work!

### ISSUE THREAD

**Issue by stuwilkins** [NSLS-II/dataportal#99]
Blows up on Stop Run Events

![image](https://cloud.githubusercontent.com/assets/1297941/6518216/d7a444ce-c371-11e4-8500-842071e88521.png)

**Comment by ericdill** [comment]
What commit of metadatastore are you running?

**Comment by stuwilkins** [comment]
What ever you guys installed... Just trying to take its last master. That will probably fix it.

**Comment by ericdill** [comment]
metadatastore master should work just fine

**Comment by stuwilkins** [comment]
Does.... now struggling with filestore

**Comment by stuwilkins** [comment]
And so it does ... sorry!
